### ISSUE TITLE
Refactor: Better handling of SpanGroup.text vs SpanGroup.symbols

### ISSUE THREAD

**Issue by kyleclo** [allenai/mmda#116]
See this PR https://github.com/allenai/mmda/pull/115 for example of trying to stitch the two together.  

We need something that's a bit more baked-into SpanGroups. For example, possibly `SpanGroup.text` is a property that wraps `SpanGroup.symbols` and postproceses using a particular `.join()` logic, but it can be overwritten with data, when available?

**Comment by soldni** [comment]
Ok this makes sense to me. I'll have the following behavior:
1. If `.text` does not exist, use `''.join(self.symbols)`
2. If `.text` has been provided, return that. 
3. `SpanGroup.text` property can be subclassed to implement more specific behavior.
